# frozen_string_literal: true

# RuboCop configuration for Prescient gem
# Modern Ruby best practices with sensible defaults

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  # Target Ruby 3.0+ (matches gemspec requirement)
  TargetRubyVersion: 3.0

  # Use new cops by default
  NewCops: enable

  # Exclude common directories
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'pkg/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'examples/**/*'

# === LAYOUT & FORMATTING ===

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'
    - 'lib/prescient.rb'  # Configuration can have long lines
  AllowedPatterns:
    - '^\s*#'  # Comments
    - '^\s*it\s'  # Test descriptions
    - '^\s*context\s'  # Test contexts
    - '^\s*describe\s'  # Test descriptions

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# === STYLE ===

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'examples/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  MinDigits: 6

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowedMethods:
    - expect
    - let
    - subject

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatString:
  EnforcedStyle: percent

Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    detect: find
    find_all: select
    reduce: inject

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# === METRICS ===

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'
    - 'lib/prescient/provider/*.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'test/**/*'
    - 'lib/prescient.rb'  # Configuration block

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'
    - 'lib/prescient/provider/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'lib/prescient/provider/*.rb'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/prescient/provider/*.rb'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# === LINT ===

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

# === NAMING ===

Naming/PredicatePrefix:
  ForbiddenPrefixes:
    - is_
  AllowedMethods:
    - is_a?

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/VariableNumber:
  EnforcedStyle: snake_case

# === SECURITY ===

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Security/JSONLoad:
  Enabled: true

# === PERFORMANCE ===

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

# === MINITEST ===

Minitest/MultipleAssertions:
  Max: 5

Minitest/AssertTruthy:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: true

Minitest/RefuteFalse:
  Enabled: true

Minitest/RefuteNil:
  Enabled: true

Minitest/TestMethodName:
  Enabled: true
