name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  id-token: write
jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --format github --format json --out rubocop-report.json

      - name: Upload RuboCop report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rubocop-report
          path: rubocop-report.json

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Run tests with coverage
        run: bundle exec rake coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          use_oidc: true
          files: ./coverage.xml,./coverage/coverage.xml,./coverage/.resultset.json
          fail_ci_if_error: false
        continue-on-error: true

  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Generate YARD documentation
        run: bundle exec yard doc

      - name: Check documentation coverage
        run: |
          bundle exec yard stats --list-undoc > undocumented.txt
          if [ -s undocumented.txt ]; then
            echo "Undocumented methods found:"
            cat undocumented.txt
            echo "Please add documentation for the above methods."
            # Don't fail the build for now, just warn
            # exit 1
          fi

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: yard-documentation
          path: doc/

  performance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Install benchmark dependencies
        run: |
          gem install benchmark-ips
          gem install memory_profiler

      - name: Run performance benchmarks
        run: |
          cat > benchmark.rb << 'EOF'
          require 'benchmark/ips'
          require 'memory_profiler'
          require_relative 'lib/prescient'

          # Simple benchmark for client creation
          Benchmark.ips do |x|
            x.report("Client.new") { Prescient::Client.new(:ollama, enable_fallback: false) }
            x.report("Client.new with fallback") { Prescient::Client.new(:ollama, enable_fallback: true) }
            x.compare!
          end

          # Memory usage benchmark
          report = MemoryProfiler.report do
            100.times { Prescient::Client.new(:ollama, enable_fallback: false) }
          end

          puts "\nMemory Usage Report:"
          puts "Total allocated: #{report.total_allocated} bytes"
          puts "Total retained: #{report.total_retained} bytes"
          EOF

          ruby benchmark.rb
